// <auto-generated />
using BlackBook_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlackBook_System.Migrations
{
    [DbContext(typeof(BlackBook_SystemContext))]
    [Migration("20250425141040_ACTION_TAKEN")]
    partial class ACTION_TAKEN
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlackBook_System.Models.Discipline", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ACTION_TAKEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADMNO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AUDITED_BY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AUDITED_DATETIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CASE_STATUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CLASS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INDISCIPLINECASE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STUDENTNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Discipline");
                });
#pragma warning restore 612, 618
        }
    }
}
