-- First chunk of locations
INSERT INTO Location (County, SubCounty, Ward) VALUES
('Mombasa', 'Changamwe', 'Port Reitz'),
('Mombasa', 'Changamwe', 'Kipevu'),
('Mombasa', 'Changamwe', 'Airport'),
('Mombasa', 'Changamwe', 'Changamwe'),
('Mombasa', 'Changamwe', 'Chaani'),
('Mombasa', 'Jomvu', 'Jomvu Kuu'),
('Mombasa', 'Jomvu', 'Miritini'),
('Mombasa', 'Jomvu', 'Mikindani'),
('Mombasa', 'Kisauni', 'Mjambere'),
('Mombasa', 'Kisauni', 'Junda'),
('Mombasa', 'Kisauni', 'Bamburi'),
('Mombasa', 'Kisauni', 'Mwakirunge'),
('Mombasa', 'Kisauni', 'Mtopanga'),
('Mombasa', 'Kisauni', 'Magogoni'),
('Mombasa', 'Kisauni', 'Shanzu'),
('Mombasa', 'Nyali', 'Frere Town'),
('Mombasa', 'Nyali', 'Ziwa La Ng''Ombe'),
('Mombasa', 'Nyali', 'Mkomani'),
('Mombasa', 'Nyali', 'Kongowea'),
('Mombasa', 'Nyali', 'Kadzandani'),
('Mombasa', 'Likoni', 'Mtongwe'),
('Mombasa', 'Likoni', 'Shika Adabu'),
('Mombasa', 'Likoni', 'Bofu'),
('Mombasa', 'Likoni', 'Likoni'),
('Mombasa', 'Likoni', 'Timbwani'),
('Mombasa', 'Mvita', 'Mji Wa Kale/Makadara'),
('Mombasa', 'Mvita', 'Tudor'),
('Mombasa', 'Mvita', 'Tononoka'),
('Mombasa', 'Mvita', 'Shimanzi/Ganjoni'),
('Mombasa', 'Mvita', 'Majengo');

-- Second chunk of locations
INSERT INTO Location (County, SubCounty, Ward) VALUES
('Kwale', 'Msambweni', 'Gombato Bongwe'),
('Kwale', 'Msambweni', 'Ukunda'),
('Kwale', 'Msambweni', 'Kinondo'),
('Kwale', 'Msambweni', 'Ramisi'),
('Kwale', 'Lungalunga', 'Pongwe/Kikoneni'),
('Kwale', 'Lungalunga', 'Dzombo'),
('Kwale', 'Lungalunga', 'Mwereni'),
('Kwale', 'Lungalunga', 'Vanga'),
('Kwale', 'Matuga', 'Tsima Golini'),
('Kwale', 'Matuga', 'Waa'),
('Kwale', 'Matuga', 'Tiwi'),
('Kwale', 'Matuga', 'Kubo South'),
('Kwale', 'Matuga', 'Mkongani'),
('Kwale', 'Kinango', 'Ndavaya'),
('Kwale', 'Kinango', 'Puma'),
('Kwale', 'Kinango', 'Kinango'),
('Kwale', 'Kinango', 'Mackinnon Road'),
('Kwale', 'Kinango', 'Chengoni/Samburu'),
('Kwale', 'Kinango', 'Mwavumbo'),
('Kwale', 'Kinango', 'Kasemeni');

-- Third chunk of locations
INSERT INTO Location (County, SubCounty, Ward) VALUES
('Kilifi', 'Kilifi North', 'Tezo'),
('Kilifi', 'Kilifi North', 'Sokoni'),
('Kilifi', 'Kilifi North', 'Kibarani'),
('Kilifi', 'Kilifi North', 'Dabaso'),
('Kilifi', 'Kilifi North', 'Matsangoni'),
('Kilifi', 'Kilifi North', 'Watamu'),
('Kilifi', 'Kilifi North', 'Mnarani'),
('Kilifi', 'Kilifi South', 'Junju'),
('Kilifi', 'Kilifi South', 'Mwarakaya'),
('Kilifi', 'Kilifi South', 'Shimo La Tewa'),
('Kilifi', 'Kilifi South', 'Chasimba'),
('Kilifi', 'Kilifi South', 'Mtepeni'),
('Kilifi', 'Kaloleni', 'Mariakani'),
('Kilifi', 'Kaloleni', 'Kayafungo'),
('Kilifi', 'Kaloleni', 'Kaloleni'),
('Kilifi', 'Kaloleni', 'Mwanamwinga'),
('Kilifi', 'Rabai', 'Mwawesa'),
('Kilifi', 'Rabai', 'Ruruma'),
('Kilifi', 'Rabai', 'Kambe/Ribe'),
('Kilifi', 'Rabai', 'Rabai/Kisurutini');

-- Fourth chunk of locations
INSERT INTO Location (County, SubCounty, Ward) VALUES
('Kilifi', 'Ganze', 'Ganze'),
('Kilifi', 'Ganze', 'Bamba'),
('Kilifi', 'Ganze', 'Jaribuni'),
('Kilifi', 'Ganze', 'Sokoke'),
('Kilifi', 'Malindi', 'Jilore'),
('Kilifi', 'Malindi', 'Kakuyuni'),
('Kilifi', 'Malindi', 'Ganda'),
('Kilifi', 'Malindi', 'Malindi Town'),
('Kilifi', 'Malindi', 'Shella'),
('Kilifi', 'Magarini', 'Marafa'),
('Kilifi', 'Magarini', 'Magarini'),
('Kilifi', 'Magarini', 'Gongoni'),
('Kilifi', 'Magarini', 'Adu'),
('Kilifi', 'Magarini', 'Garashi'),
('Kilifi', 'Magarini', 'Sabaki');

-- Fifth chunk of locations
INSERT INTO Location (County, SubCounty, Ward) VALUES
('Tana River', 'Garsen', 'Kipini East'),
('Tana River', 'Garsen', 'Garsen South'),
('Tana River', 'Garsen', 'Kipini West'),
('Tana River', 'Garsen', 'Garsen Central'),
('Tana River', 'Garsen', 'Garsen West'),
('Tana River', 'Garsen', 'Garsen North'),
('Tana River', 'Galole', 'Kinakomba'),
('Tana River', 'Galole', 'Mikinduni'),
('Tana River', 'Galole', 'Chewani'),
('Tana River', 'Galole', 'Wayu'),
('Tana River', 'Bura', 'Chewele'),
('Tana River', 'Bura', 'Hirimani'),
('Tana River', 'Bura', 'Bangale'),
('Tana River', 'Bura', 'Sala'),
('Tana River', 'Bura', 'Madogo');

-- Sixth chunk of locations
INSERT INTO Location (County, SubCounty, Ward) VALUES
('Lamu', 'Lamu East', 'Faza'),
('Lamu', 'Lamu East', 'Kiunga'),
('Lamu', 'Lamu East', 'Basuba'),
('Lamu', 'Lamu West', 'Shella'),
('Lamu', 'Lamu West', 'Mkomani'),
('Lamu', 'Lamu West', 'Hindi'),
('Lamu', 'Lamu West', 'Mkunumbi'),
('Lamu', 'Lamu West', 'Hongwe'),
('Lamu', 'Lamu West', 'Witu'),
('Lamu', 'Lamu West', 'Bahari');

-- Seventh chunk of locations
INSERT INTO Location (County, SubCounty, Ward) VALUES
('Taita Taveta', 'Taveta', 'Chala'),
('Taita Taveta', 'Taveta', 'Mahoo'),
('Taita Taveta', 'Taveta', 'Bomani'),
('Taita Taveta', 'Taveta', 'Mboghoni'),
('Taita Taveta', 'Taveta', 'Mata'),
('Taita Taveta', 'Wundanyi', 'Wundanyi/Mbale'),
('Taita Taveta', 'Wundanyi', 'Werugha'),
('Taita Taveta', 'Wundanyi', 'Wumingu/Kishushe'),
('Taita Taveta', 'Wundanyi', 'Mwanda/Mgange'),
('Taita Taveta', 'Mwatate', 'Rong''E'),
('Taita Taveta', 'Mwatate', 'Mwatate'),
('Taita Taveta', 'Mwatate', 'Bura'),
('Taita Taveta', 'Mwatate', 'Chawia'),
('Taita Taveta', 'Mwatate', 'Wusi/Kishamba'),
('Taita Taveta', 'Voi', 'Mbololo'),
('Taita Taveta', 'Voi', 'Sagalla'),
('Taita Taveta', 'Voi', 'Kaloleni'),
('Taita Taveta', 'Voi', 'Marungu'),
('Taita Taveta', 'Voi', 'Kasigau'),
('Taita Taveta', 'Voi', 'Ngolia'); 