-- Eighth chunk of locations
INSERT INTO Location (County, SubCounty, Ward) VALUES
('Garissa', 'Garissa Township', 'Waberi'),
('Garissa', 'Garissa Township', 'Galbet'),
('Garissa', 'Garissa Township', 'Township'),
('Garissa', 'Garissa Township', 'Iftin'),
('Garissa', 'Balambala', 'Balambala'),
('Garissa', 'Balambala', 'Danyere'),
('Garissa', 'Balambala', 'Jara Jara'),
('Garissa', 'Balambala', 'Saka'),
('Garissa', 'Balambala', 'Sankuri'),
('Garissa', 'Lagdera', 'Modogashe'),
('Garissa', 'Lagdera', 'Benane'),
('Garissa', 'Lagdera', 'Goreale'),
('Garissa', 'Lagdera', 'Maalimin'),
('Garissa', 'Lagdera', 'Sabena'),
('Garissa', 'Lagdera', 'Baraki'),
('Garissa', 'Dadaab', 'Dertu'),
('Garissa', 'Dadaab', 'Dadaab'),
('Garissa', 'Dadaab', 'Labasigale'),
('Garissa', 'Dadaab', 'Damajale'),
('Garissa', 'Dadaab', 'Liboi'),
('Garissa', 'Dadaab', 'Abakaile');

-- Ninth chunk of locations
INSERT INTO Location (County, SubCounty, Ward) VALUES
('Garissa', 'Fafi', 'Bura'),
('Garissa', 'Fafi', 'Dekaharia'),
('Garissa', 'Fafi', 'Jarajila'),
('Garissa', 'Fafi', 'Fafi'),
('Garissa', 'Fafi', 'Nanighi'),
('Garissa', 'Ijara', 'Hulugho'),
('Garissa', 'Ijara', 'Sangailu'),
('Garissa', 'Ijara', 'Ijara'),
('Garissa', 'Ijara', 'Masalani'),
('Wajir', 'Wajir North', 'Gurar'),
('Wajir', 'Wajir North', 'Bute'),
('Wajir', 'Wajir North', 'Korondile'),
('Wajir', 'Wajir North', 'Malkagufu'),
('Wajir', 'Wajir North', 'Batalu'),
('Wajir', 'Wajir North', 'Danaba'),
('Wajir', 'Wajir North', 'Godoma'),
('Wajir', 'Wajir East', 'Wagberi'),
('Wajir', 'Wajir East', 'Township'),
('Wajir', 'Wajir East', 'Barwago'),
('Wajir', 'Wajir East', 'Khorof/Harar');

-- Tenth chunk of locations
INSERT INTO Location (County, SubCounty, Ward) VALUES
('Wajir', 'Tarbaj', 'Elben'),
('Wajir', 'Tarbaj', 'Sarman'),
('Wajir', 'Tarbaj', 'Tarbaj'),
('Wajir', 'Tarbaj', 'Wargadud'),
('Wajir', 'Wajir West', 'Arbajahan'),
('Wajir', 'Wajir West', 'Hadado/Athibohol'),
('Wajir', 'Wajir West', 'Adamasajide'),
('Wajir', 'Wajir West', 'Ganyure/Wagalla'),
('Wajir', 'Eldas', 'Eldas'),
('Wajir', 'Eldas', 'Della'),
('Wajir', 'Eldas', 'Lakoley South/Basir'),
('Wajir', 'Eldas', 'Elnur/Tula Tula'),
('Wajir', 'Wajir South', 'Benane'),
('Wajir', 'Wajir South', 'Burder'),
('Wajir', 'Wajir South', 'Dadaja Bulla'),
('Wajir', 'Wajir South', 'Habasswein'),
('Wajir', 'Wajir South', 'Lagboghol South'),
('Wajir', 'Wajir South', 'Ibrahim Ure'),
('Wajir', 'Wajir South', 'Diif');

-- Eleventh chunk of locations
INSERT INTO Location (County, SubCounty, Ward) VALUES
('Mandera', 'Mandera West', 'Takaba South'),
('Mandera', 'Mandera West', 'Takaba'),
('Mandera', 'Mandera West', 'Lagsure'),
('Mandera', 'Mandera West', 'Dandu'),
('Mandera', 'Mandera West', 'Gither'),
('Mandera', 'Banissa', 'Banissa'),
('Mandera', 'Banissa', 'Derkhale'),
('Mandera', 'Banissa', 'Guba'),
('Mandera', 'Banissa', 'Malkamari'),
('Mandera', 'Banissa', 'Kiliwehiri'),
('Mandera', 'Mandera North', 'Ashabito'),
('Mandera', 'Mandera North', 'Guticha'),
('Mandera', 'Mandera North', 'Morothile'),
('Mandera', 'Mandera North', 'Rhamu'),
('Mandera', 'Mandera North', 'Rhamu-Dimtu'),
('Mandera', 'Mandera South', 'Wargadud'),
('Mandera', 'Mandera South', 'Kutulo'),
('Mandera', 'Mandera South', 'Elwak South'),
('Mandera', 'Mandera South', 'Elwak North'),
('Mandera', 'Mandera South', 'Shimbir Fatuma');

-- Twelfth chunk of locations
INSERT INTO Location (County, SubCounty, Ward) VALUES
('Mandera', 'Mandera East', 'Arabia'),
('Mandera', 'Mandera East', 'Township'),
('Mandera', 'Mandera East', 'Neboi'),
('Mandera', 'Mandera East', 'Khalalio'),
('Mandera', 'Mandera East', 'Libehia'),
('Mandera', 'Lafey', 'Sala'),
('Mandera', 'Lafey', 'Fino'),
('Mandera', 'Lafey', 'Lafey'),
('Mandera', 'Lafey', 'Waranqara'),
('Mandera', 'Lafey', 'Alango Gof'),
('Marsabit', 'Moyale', 'Butiye'),
('Marsabit', 'Moyale', 'Sololo'),
('Marsabit', 'Moyale', 'Heillu/Manyatta'),
('Marsabit', 'Moyale', 'Golbo'),
('Marsabit', 'Moyale', 'Moyale Township'),
('Marsabit', 'Moyale', 'Uran'),
('Marsabit', 'Moyale', 'Obbu'),
('Marsabit', 'North Horr', 'Dukana'),
('Marsabit', 'North Horr', 'Maikona'),
('Marsabit', 'North Horr', 'Turbi'); 